### ISSUE TITLE
Assemblies shouldn't be loaded from app domain's base path

### ISSUE THREAD

**Issue by MrJul** [KathleenDollard/RoslynDOM#100]
Hello,

First of all, thank you for this project: it helps a lot working with Roslyn when you don't need all the advanced compiler stuff.

I've got an issue with how RoslynDOM assemblies are loaded through Unity's `AllClasses.FromAssembliesInBasePath`. This poses two problems:
- A bunch of unnecessary assemblies present in the app domain's base path are loaded.
- Nothing is registered if RoslynDOM assemblies aren't in this specific directory. Thus, RoslynDOM fails as soon as a component is needed.

IMHO, in a more general way, a library should never scan for extra assemblies, that's the responsibility of the host application.

In my use case, the host is VS and the assemblies aren't at all next to devenv.exe.

To fix this, I'm thinking about explicitly adding assemblies to the configured container: `RoslynDom`, `RoslynDomCommon`, `RoslynDomRDomCommon`, plus the correct language assembly (an extra `IEnumerable<Assembly>` parameter can be passed to `RDomCorporation`'s constructor, or `factoryAccess.GetType().Assembly` can be used directly (less flexible)).

Current fix implemented on my fork: https://github.com/MrJul/RoslynDOM/commit/28551ff986286820e21665b3ca1b2102228a841a
If you're interested in this fix, I can make a pull request.

**Comment by KathleenDollard** [comment]
It looks like you found a significant design flaw, that I overlooked because I do all my work in tests.

I'm just looking at this, but it looks like the DI in general is screwed up. Your fork is a step forward, and I think it makes sense to take it. But it looks like a breaking change. Could you modify this:

- in RoslynDomRDomCommon/Provider.cs ConfigureContainer, could you make the use of your approach optional, based on whether any specific assemblies are passed
- Would a parameter array (params) be better here?
- Walking this change back through the other two locations, making the specification of assemblies optional

How does that sound?

I'd also like to more broadly discuss making DI work. Such as allowing the calling code to specify some or all of the assemblies that are loaded. That looks like an extension of your fork to have the caller specify, or use the default, for each of the expected assemblies. I'm currently seeing non-elegance in implementation, so I think it makes sense to take the first step of getting your PR in,and then figure this out.

**Comment by MrJul** [comment]
- I can do that. Aren't two different methods better though (`ConfigureDefaultContainer` and `ConfigureContainer`, both calling a common private method)? If an empty array passed as `extraAssemblies` is potentially loading a bunch of extra assemblies, it feels odd to me.

- I always hesitate between `params` and `IEnumerable`. Too bad `params IEnumerable` didn't make it into C# 6 :( Here the code is fully internal so params doesn't really help the end user. That said, I will change into what you prefer.

- OK, it was weird to specify the assemblies in test code.

I'm preparing a pull request with my current changes: I will push additional commits to it to take your remarks into account.
