### ISSUE TITLE
Empty region causes NullReferenceException

### ISSUE THREAD

**Issue by wwrafter** [KathleenDollard/RoslynDOM#96]
var csharpCode = 
@"  
public class MyClass
{ 
    #region Properties
    #endregion
}";
          var root = RDom.CSharp.Load(csharpCode);

**Comment by KathleenDollard** [comment]
I receive a "Sequence contains no elements" , not "Null-reference"

(in process of fixing)

**Comment by KathleenDollard** [comment]
This was the tip of a small iceberg. 

The underlying problem is how regions are matched up. Previously, this was done on load and therefore something between the open/close needed to push the start into the DOM before the end could find it.

This was an overall bad design, and after spending a bit of time this morning, I decided the cleanest of all imperfect approaches is to have a fixup process run after the DOM is loaded. This secondary process matches on the contained trivia's GetRelated... method and syncs up the Guids. 

This is currently in the Root factory, which I think is a valid location

As a deliberate side effect of this fix, randomly placed regions are now supported along with a flag to indicate whether nesting is semantically correct (issue #99)
